name: Hollywood Stuntworks
favicon: null
layout_spectrum: 0.7835
typography_spectrum: 0.84241
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#360000'
    - '#fed38e'
    - '#6b6b61'
    - '#92aa8a'
    - '#4d3860'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
